#define RELAY 0 // relay connected to  GPIO0
#define RELAY_OFF_TIME_MS 10000
#define LOOP_SLEEP_MS 5000

#define MAX_DISCONNECT_TIME_MINUTES 2
#define MAX_DISCONNECT_TIME_MS 60000*MAX_DISCONNECT_TIME_MINUTES 